// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC8zZhZzKsHiRc9OBh0-PfQ72NdjSrmk4',
    appId: '1:625069713034:web:d12373b701d4c03731af73',
    messagingSenderId: '625069713034',
    projectId: 'karbon-ayak-izi-30b69',
    authDomain: 'karbon-ayak-izi-30b69.firebaseapp.com',
    storageBucket: 'karbon-ayak-izi-30b69.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX-93bdm93Eme0qreTUFyPwCP4Jr0uu0Q',
    appId: '1:625069713034:android:ad3d8a847881fe8231af73',
    messagingSenderId: '625069713034',
    projectId: 'karbon-ayak-izi-30b69',
    storageBucket: 'karbon-ayak-izi-30b69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyLT-njWtn-nzZhNhFSUjI98O6E8GE-sc',
    appId: '1:625069713034:ios:16db617864cd4d9531af73',
    messagingSenderId: '625069713034',
    projectId: 'karbon-ayak-izi-30b69',
    storageBucket: 'karbon-ayak-izi-30b69.appspot.com',
    iosClientId: '625069713034-bn897lll7mj9buo3o8e5r0gm3hvrs57m.apps.googleusercontent.com',
    iosBundleId: 'com.example.karbonAyakIziApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyLT-njWtn-nzZhNhFSUjI98O6E8GE-sc',
    appId: '1:625069713034:ios:16db617864cd4d9531af73',
    messagingSenderId: '625069713034',
    projectId: 'karbon-ayak-izi-30b69',
    storageBucket: 'karbon-ayak-izi-30b69.appspot.com',
    iosClientId: '625069713034-bn897lll7mj9buo3o8e5r0gm3hvrs57m.apps.googleusercontent.com',
    iosBundleId: 'com.example.karbonAyakIziApp',
  );
}
